/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CorePoint from './CorePoint';

/**
 * The CoreSpan model module.
 * @module model/CoreSpan
 * @version 1.0
 */
class CoreSpan {
    /**
     * Constructs a new <code>CoreSpan</code>.
     * @alias module:model/CoreSpan
     */
    constructor() { 
        
        CoreSpan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoreSpan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoreSpan} obj Optional instance to populate.
     * @return {module:model/CoreSpan} The populated <code>CoreSpan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoreSpan();

            if (data.hasOwnProperty('end')) {
                obj['end'] = CorePoint.constructFromObject(data['end']);
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = CorePoint.constructFromObject(data['start']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CoreSpan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CoreSpan</code>.
     */
    static validateJSON(data) {
        // validate the optional field `end`
        if (data['end']) { // data not null
          CorePoint.validateJSON(data['end']);
        }
        // validate the optional field `start`
        if (data['start']) { // data not null
          CorePoint.validateJSON(data['start']);
        }

        return true;
    }


}



/**
 * @member {module:model/CorePoint} end
 */
CoreSpan.prototype['end'] = undefined;

/**
 * @member {module:model/CorePoint} start
 */
CoreSpan.prototype['start'] = undefined;






export default CoreSpan;

