/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoreSpan from './CoreSpan';

/**
 * The Sibyl2ClazzWithPath model module.
 * @module model/Sibyl2ClazzWithPath
 * @version 1.0
 */
class Sibyl2ClazzWithPath {
    /**
     * Constructs a new <code>Sibyl2ClazzWithPath</code>.
     * @alias module:model/Sibyl2ClazzWithPath
     */
    constructor() { 
        
        Sibyl2ClazzWithPath.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Sibyl2ClazzWithPath</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sibyl2ClazzWithPath} obj Optional instance to populate.
     * @return {module:model/Sibyl2ClazzWithPath} The populated <code>Sibyl2ClazzWithPath</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sibyl2ClazzWithPath();

            if (data.hasOwnProperty('extras')) {
                obj['extras'] = ApiClient.convertToType(data['extras'], Object);
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ApiClient.convertToType(data['lang'], 'String');
            }
            if (data.hasOwnProperty('module')) {
                obj['module'] = ApiClient.convertToType(data['module'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('span')) {
                obj['span'] = CoreSpan.constructFromObject(data['span']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Sibyl2ClazzWithPath</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Sibyl2ClazzWithPath</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['lang'] && !(typeof data['lang'] === 'string' || data['lang'] instanceof String)) {
            throw new Error("Expected the field `lang` to be a primitive type in the JSON string but got " + data['lang']);
        }
        // ensure the json data is a string
        if (data['module'] && !(typeof data['module'] === 'string' || data['module'] instanceof String)) {
            throw new Error("Expected the field `module` to be a primitive type in the JSON string but got " + data['module']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // validate the optional field `span`
        if (data['span']) { // data not null
          CoreSpan.validateJSON(data['span']);
        }

        return true;
    }


}



/**
 * which contains language-specific contents
 * @member {Object} extras
 */
Sibyl2ClazzWithPath.prototype['extras'] = undefined;

/**
 * language
 * @member {String} lang
 */
Sibyl2ClazzWithPath.prototype['lang'] = undefined;

/**
 * @member {String} module
 */
Sibyl2ClazzWithPath.prototype['module'] = undefined;

/**
 * @member {String} name
 */
Sibyl2ClazzWithPath.prototype['name'] = undefined;

/**
 * @member {String} path
 */
Sibyl2ClazzWithPath.prototype['path'] = undefined;

/**
 * @member {module:model/CoreSpan} span
 */
Sibyl2ClazzWithPath.prototype['span'] = undefined;






export default Sibyl2ClazzWithPath;

