/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Sibyl2FunctionContextSlim from '../model/Sibyl2FunctionContextSlim';

/**
* ReferenceQuery service.
* @module api/ReferenceQueryApi
* @version 1.0
*/
export default class ReferenceQueryApi {

    /**
    * Constructs a new ReferenceQueryApi. 
    * @alias module:api/ReferenceQueryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV1ReferenceCountFuncctxGet operation.
     * @callback module:api/ReferenceQueryApi~apiV1ReferenceCountFuncctxGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sibyl2FunctionContextSlim>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * funcctx query by ref
     * @param {String} repo repo
     * @param {String} rev rev
     * @param {Number} moreThan moreThan
     * @param {Number} lessThan lessThan
     * @param {module:api/ReferenceQueryApi~apiV1ReferenceCountFuncctxGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sibyl2FunctionContextSlim>}
     */
    apiV1ReferenceCountFuncctxGet(repo, rev, moreThan, lessThan, callback) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling apiV1ReferenceCountFuncctxGet");
      }
      // verify the required parameter 'rev' is set
      if (rev === undefined || rev === null) {
        throw new Error("Missing the required parameter 'rev' when calling apiV1ReferenceCountFuncctxGet");
      }
      // verify the required parameter 'moreThan' is set
      if (moreThan === undefined || moreThan === null) {
        throw new Error("Missing the required parameter 'moreThan' when calling apiV1ReferenceCountFuncctxGet");
      }
      // verify the required parameter 'lessThan' is set
      if (lessThan === undefined || lessThan === null) {
        throw new Error("Missing the required parameter 'lessThan' when calling apiV1ReferenceCountFuncctxGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'rev': rev,
        'moreThan': moreThan,
        'lessThan': lessThan
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Sibyl2FunctionContextSlim];
      return this.apiClient.callApi(
        '/api/v1/reference/count/funcctx', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1ReferenceCountFuncctxReverseGet operation.
     * @callback module:api/ReferenceQueryApi~apiV1ReferenceCountFuncctxReverseGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sibyl2FunctionContextSlim>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * funcctx query by referenced
     * @param {String} repo repo
     * @param {String} rev rev
     * @param {Number} moreThan moreThan
     * @param {Number} lessThan lessThan
     * @param {module:api/ReferenceQueryApi~apiV1ReferenceCountFuncctxReverseGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sibyl2FunctionContextSlim>}
     */
    apiV1ReferenceCountFuncctxReverseGet(repo, rev, moreThan, lessThan, callback) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling apiV1ReferenceCountFuncctxReverseGet");
      }
      // verify the required parameter 'rev' is set
      if (rev === undefined || rev === null) {
        throw new Error("Missing the required parameter 'rev' when calling apiV1ReferenceCountFuncctxReverseGet");
      }
      // verify the required parameter 'moreThan' is set
      if (moreThan === undefined || moreThan === null) {
        throw new Error("Missing the required parameter 'moreThan' when calling apiV1ReferenceCountFuncctxReverseGet");
      }
      // verify the required parameter 'lessThan' is set
      if (lessThan === undefined || lessThan === null) {
        throw new Error("Missing the required parameter 'lessThan' when calling apiV1ReferenceCountFuncctxReverseGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'rev': rev,
        'moreThan': moreThan,
        'lessThan': lessThan
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Sibyl2FunctionContextSlim];
      return this.apiClient.callApi(
        '/api/v1/reference/count/funcctx/reverse', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
