/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Sibyl2ClazzWithPath from '../model/Sibyl2ClazzWithPath';
import Sibyl2FunctionContextSlim from '../model/Sibyl2FunctionContextSlim';
import Sibyl2FunctionWithPath from '../model/Sibyl2FunctionWithPath';

/**
* RegexQuery service.
* @module api/RegexQueryApi
* @version 1.0
*/
export default class RegexQueryApi {

    /**
    * Constructs a new RegexQueryApi. 
    * @alias module:api/RegexQueryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV1RegexClazzGet operation.
     * @callback module:api/RegexQueryApi~apiV1RegexClazzGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sibyl2ClazzWithPath>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * clazz query
     * @param {String} repo repo
     * @param {String} rev rev
     * @param {String} field field
     * @param {String} regex regex
     * @param {module:api/RegexQueryApi~apiV1RegexClazzGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sibyl2ClazzWithPath>}
     */
    apiV1RegexClazzGet(repo, rev, field, regex, callback) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling apiV1RegexClazzGet");
      }
      // verify the required parameter 'rev' is set
      if (rev === undefined || rev === null) {
        throw new Error("Missing the required parameter 'rev' when calling apiV1RegexClazzGet");
      }
      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling apiV1RegexClazzGet");
      }
      // verify the required parameter 'regex' is set
      if (regex === undefined || regex === null) {
        throw new Error("Missing the required parameter 'regex' when calling apiV1RegexClazzGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'rev': rev,
        'field': field,
        'regex': regex
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Sibyl2ClazzWithPath];
      return this.apiClient.callApi(
        '/api/v1/regex/clazz', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1RegexFuncGet operation.
     * @callback module:api/RegexQueryApi~apiV1RegexFuncGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sibyl2FunctionWithPath>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * func query
     * @param {String} repo repo
     * @param {String} rev rev
     * @param {String} field field
     * @param {String} regex regex
     * @param {module:api/RegexQueryApi~apiV1RegexFuncGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sibyl2FunctionWithPath>}
     */
    apiV1RegexFuncGet(repo, rev, field, regex, callback) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling apiV1RegexFuncGet");
      }
      // verify the required parameter 'rev' is set
      if (rev === undefined || rev === null) {
        throw new Error("Missing the required parameter 'rev' when calling apiV1RegexFuncGet");
      }
      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling apiV1RegexFuncGet");
      }
      // verify the required parameter 'regex' is set
      if (regex === undefined || regex === null) {
        throw new Error("Missing the required parameter 'regex' when calling apiV1RegexFuncGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'rev': rev,
        'field': field,
        'regex': regex
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Sibyl2FunctionWithPath];
      return this.apiClient.callApi(
        '/api/v1/regex/func', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1RegexFuncctxGet operation.
     * @callback module:api/RegexQueryApi~apiV1RegexFuncctxGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sibyl2FunctionContextSlim>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * func ctx query
     * @param {String} repo repo
     * @param {String} rev rev
     * @param {String} field field
     * @param {String} regex regex
     * @param {module:api/RegexQueryApi~apiV1RegexFuncctxGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sibyl2FunctionContextSlim>}
     */
    apiV1RegexFuncctxGet(repo, rev, field, regex, callback) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling apiV1RegexFuncctxGet");
      }
      // verify the required parameter 'rev' is set
      if (rev === undefined || rev === null) {
        throw new Error("Missing the required parameter 'rev' when calling apiV1RegexFuncctxGet");
      }
      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling apiV1RegexFuncctxGet");
      }
      // verify the required parameter 'regex' is set
      if (regex === undefined || regex === null) {
        throw new Error("Missing the required parameter 'regex' when calling apiV1RegexFuncctxGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'rev': rev,
        'field': field,
        'regex': regex
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Sibyl2FunctionContextSlim];
      return this.apiClient.callApi(
        '/api/v1/regex/funcctx', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
