/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiForSibyl2Server);
  }
}(this, function(expect, OpenapiForSibyl2Server) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Sibyl2ClazzWithPath', function() {
    it('should create an instance of Sibyl2ClazzWithPath', function() {
      // uncomment below and update the code to test Sibyl2ClazzWithPath
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be.a(OpenapiForSibyl2Server.Sibyl2ClazzWithPath);
    });

    it('should have the property extras (base name: "extras")', function() {
      // uncomment below and update the code to test the property extras
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

    it('should have the property lang (base name: "lang")', function() {
      // uncomment below and update the code to test the property lang
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

    it('should have the property module (base name: "module")', function() {
      // uncomment below and update the code to test the property module
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

    it('should have the property span (base name: "span")', function() {
      // uncomment below and update the code to test the property span
      //var instance = new OpenapiForSibyl2Server.Sibyl2ClazzWithPath();
      //expect(instance).to.be();
    });

  });

}));
