/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CorePoint from './model/CorePoint';
import CoreSpan from './model/CoreSpan';
import ObjectFunctionContextSlimWithSignature from './model/ObjectFunctionContextSlimWithSignature';
import ObjectFunctionWithSignature from './model/ObjectFunctionWithSignature';
import ObjectRevInfo from './model/ObjectRevInfo';
import ObjectValueUnit from './model/ObjectValueUnit';
import ServiceContextTree from './model/ServiceContextTree';
import ServiceFunctionContextChain from './model/ServiceFunctionContextChain';
import ServiceRevStat from './model/ServiceRevStat';
import Sibyl2ClazzWithPath from './model/Sibyl2ClazzWithPath';
import Sibyl2FunctionContextSlim from './model/Sibyl2FunctionContextSlim';
import Sibyl2FunctionWithPath from './model/Sibyl2FunctionWithPath';
import BasicQueryApi from './api/BasicQueryApi';
import OpsApi from './api/OpsApi';
import ReferenceQueryApi from './api/ReferenceQueryApi';
import RegexQueryApi from './api/RegexQueryApi';
import ScopeApi from './api/ScopeApi';
import SignatureQueryApi from './api/SignatureQueryApi';
import StatQueryApi from './api/StatQueryApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenapiForSibyl2Server = require('index'); // See note below*.
* var xxxSvc = new OpenapiForSibyl2Server.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenapiForSibyl2Server.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenapiForSibyl2Server.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenapiForSibyl2Server.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CorePoint model constructor.
     * @property {module:model/CorePoint}
     */
    CorePoint,

    /**
     * The CoreSpan model constructor.
     * @property {module:model/CoreSpan}
     */
    CoreSpan,

    /**
     * The ObjectFunctionContextSlimWithSignature model constructor.
     * @property {module:model/ObjectFunctionContextSlimWithSignature}
     */
    ObjectFunctionContextSlimWithSignature,

    /**
     * The ObjectFunctionWithSignature model constructor.
     * @property {module:model/ObjectFunctionWithSignature}
     */
    ObjectFunctionWithSignature,

    /**
     * The ObjectRevInfo model constructor.
     * @property {module:model/ObjectRevInfo}
     */
    ObjectRevInfo,

    /**
     * The ObjectValueUnit model constructor.
     * @property {module:model/ObjectValueUnit}
     */
    ObjectValueUnit,

    /**
     * The ServiceContextTree model constructor.
     * @property {module:model/ServiceContextTree}
     */
    ServiceContextTree,

    /**
     * The ServiceFunctionContextChain model constructor.
     * @property {module:model/ServiceFunctionContextChain}
     */
    ServiceFunctionContextChain,

    /**
     * The ServiceRevStat model constructor.
     * @property {module:model/ServiceRevStat}
     */
    ServiceRevStat,

    /**
     * The Sibyl2ClazzWithPath model constructor.
     * @property {module:model/Sibyl2ClazzWithPath}
     */
    Sibyl2ClazzWithPath,

    /**
     * The Sibyl2FunctionContextSlim model constructor.
     * @property {module:model/Sibyl2FunctionContextSlim}
     */
    Sibyl2FunctionContextSlim,

    /**
     * The Sibyl2FunctionWithPath model constructor.
     * @property {module:model/Sibyl2FunctionWithPath}
     */
    Sibyl2FunctionWithPath,

    /**
    * The BasicQueryApi service constructor.
    * @property {module:api/BasicQueryApi}
    */
    BasicQueryApi,

    /**
    * The OpsApi service constructor.
    * @property {module:api/OpsApi}
    */
    OpsApi,

    /**
    * The ReferenceQueryApi service constructor.
    * @property {module:api/ReferenceQueryApi}
    */
    ReferenceQueryApi,

    /**
    * The RegexQueryApi service constructor.
    * @property {module:api/RegexQueryApi}
    */
    RegexQueryApi,

    /**
    * The ScopeApi service constructor.
    * @property {module:api/ScopeApi}
    */
    ScopeApi,

    /**
    * The SignatureQueryApi service constructor.
    * @property {module:api/SignatureQueryApi}
    */
    SignatureQueryApi,

    /**
    * The StatQueryApi service constructor.
    * @property {module:api/StatQueryApi}
    */
    StatQueryApi
};
