/**
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiForSibyl2Server);
  }
}(this, function(expect, OpenapiForSibyl2Server) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiForSibyl2Server.SignatureQueryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignatureQueryApi', function() {
    describe('apiV1SignatureFuncGet', function() {
      it('should call apiV1SignatureFuncGet successfully', function(done) {
        //uncomment below and update the code to test apiV1SignatureFuncGet
        //instance.apiV1SignatureFuncGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1SignatureFuncctxChainGet', function() {
      it('should call apiV1SignatureFuncctxChainGet successfully', function(done) {
        //uncomment below and update the code to test apiV1SignatureFuncctxChainGet
        //instance.apiV1SignatureFuncctxChainGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1SignatureFuncctxGet', function() {
      it('should call apiV1SignatureFuncctxGet successfully', function(done) {
        //uncomment below and update the code to test apiV1SignatureFuncctxGet
        //instance.apiV1SignatureFuncctxGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1SignatureFuncctxRchainGet', function() {
      it('should call apiV1SignatureFuncctxRchainGet successfully', function(done) {
        //uncomment below and update the code to test apiV1SignatureFuncctxRchainGet
        //instance.apiV1SignatureFuncctxRchainGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1SignatureRegexFuncGet', function() {
      it('should call apiV1SignatureRegexFuncGet successfully', function(done) {
        //uncomment below and update the code to test apiV1SignatureRegexFuncGet
        //instance.apiV1SignatureRegexFuncGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
